// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjmohrfoxelljychoyco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqbW9ocmZveGVsbGp5Y2hveWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzY4MzAsImV4cCI6MjA2OTc1MjgzMH0.r21F9VYiiw6GUWGFt_mr_re4kN-DXBw_IDNsr-qRzpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});